services:
  db:
    container_name: ${DB_HOST}
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    command: bash -c "fastapi run main.py --port 8000"
    volumes:
      - .:/app
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
    depends_on:
      - app


